### ISSUE TITLE
Falcon and Raptor use different versions of goblin

### ISSUE THREAD

**Issue by 2over12** [falconre/raptor#1]
This results in 2 versions of goblin being used in the project. This causes Raptor to fail to build due to the From implementation on error::Error for goblin::error::Error being for the wrong version of goblin to handle the conversion in program_translator.rs:71. Bumping the raptor version of goblin to 0.0.23 fixes this issue.

Alternatively, if goblin versions should not be synced I think in raptor falcon's version of a goblin Error could be added as an additional foreign-link.

By the way, thanks for pointing me towards falcon, going to probably move forward with implementing interprocedural fixed-point analysis over raptor, thinking it would be cool to incorporate analysis results into the raptor-gui as well.

**Comment by endeav0r** [comment]
working...

**Comment by endeav0r** [comment]
@2over12 If you have interest, and it will speed up your work, I can add you to the falconre group, and you can push changes straight to master.

**Comment by endeav0r** [comment]
This should be fixed with 306392fcd74dc3f09a32ad. I'm going to go ahead and add you to falconre so you can make changes as needed.

**Comment by endeav0r** [comment]
This should be resolved. Close when ready.

**Comment by endeav0r** [comment]
Also, went ahead and pushed https://crates.io/crates/falcon-raptor, which should have no build problems.
